project:
  type: website

filters:
  - note-status.lua

website:
  title: "Richard Costa"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: posts
      - href: notes.qmd
        text: notes
      - href: resources.qmd
        text: resources


format:
  html:
    theme: lux
    css: styles.css
    toc: true



